### ISSUE TITLE
Command-Line Interface docs out of date

### ISSUE THREAD

**Issue by LindaNab** [sodascience/metasyn#291] opened 2024-04-17 18:46 UTC
Hi `metasyn`-developers,

I'm playing around with `metasyn` (it's awesome!) and while using the CLI functionality to check out some of the basic commands I got across an error message I could not resolve. I think the documentation on readthedocs might be a bit out of sync with the current version of `metasyn`? 

In specific, I was hoping to create a `.json` file using a user defined `.toml` file (without an input CSV file). According to your documentation under this [section](https://metasyn.readthedocs.io/en/latest/usage/cli.html#creating-generative-metadata), an example `.toml` file is:
```
n_rows = 100


[[var]]

name = "PassengerId"
data_free = true
prop_missing = 0.0
description = "ID of the unfortunate passenger."
var_type = "discrete"
distribution = {implements = "core.unique_key", unique = true, parameters = {consecutive = 1, lower = 0}}
```

When I subsequently try to run:
```
metasyn create-meta --config my_config.toml --output my_gmf.json
```
I get the following error message: (truncated)
```
jsonschema.exceptions.ValidationError: {'implements': 'core.unique_key', 'version': '1.0', 'provenance': 'builtin', 'class_name': 'UniqueKeyDistribution', 'unique': True, 'parameters': {'lower': 1, 'consecutive': 1}} is not valid under any of the given schemas
Failed validating 'anyOf' in schema['properties']['vars']['items']['properties']['distribution']:
[...]
```
Please note that I changed `low` as per your documentation to `lower` in my `.toml` as I figured `low` isn't a parameter of the `core.unique_key` distribution while `lower` is. I also added the argument `--output` before my output file in the CLI command. The argument `--output` was not listed in your documentation but without `--output` the output of `metasyn create-meta` is printed in the terminal and not saved to the output file, but please correct me if I'm wrong...

I did manage to implement the `core.truncated_normal` distribution but can't figure how to make `core.unique_key` work... I tried several combinations of the parameters `lower` and `consecutive` but according to the error message their type is a `integer` and `boolean` respectively, so I can't really make sense of the error. Help would be much appreciated!

Best wishes,
Linda Nab

**Comment by qubixes** [comment] 2024-04-17 21:24
Hi @LindaNab,

Thanks for the opening an issue, and you're right the documentation is indeed out of date!

I can reproduce the error with the latest version of metasyn (main branch). I can fix it on my end by setting `consecutive = true`. Does the example work for you then?

We'll fix the example in the documentation. Also, I agree that the error is not very easy to understand (or indeed gives a lot of information). We'll also look into that.

**Comment by LindaNab** [comment] 2024-04-18 08:59
Hi @qubixes, thank you for the quick response!
Setting `consecutive = true` fixes the problem! Thanks. FYI I'm using version 0.8.0 (installed using `pip`). 
Is there by any chance an overview of distributions and their (required) parameters? I can use the error message but I'm sure there's an easier way :). 
Thanks again!

**Comment by qubixes** [comment] 2024-04-18 09:24
@LindaNab Not at the moment, but indeed when you asked the question I realized that would be a nice page on readthedocs. You can look into the API:

https://metasyn.readthedocs.io/en/latest/api/metasyn.distribution.html#module-metasyn.distribution.categorical

However, that needs a bit of work as well. The easiest way might be to simply look into the source code itself:

https://github.com/sodascience/metasyn/tree/main/metasyn/distribution

You can ignore `__init__.py` and `base.py`. The `__init__` and  `default_distribution` should give you an idea on how it can be used.

I'll keep this issue open until we have improved the documentation on this. Feel free to ask more questions!

**Comment by LindaNab** [comment] 2024-04-18 13:52
Cool. Thanks a lot. I'm planning to try out some of the distributions next week and might come back to you with further questions (will open another issue if not related to this one).

**Comment by qubixes** [comment] 2024-05-13 15:39
I'll close this issue for now, since it should be resolved with the latest version of the documentation.

**Closed by qubixes** 2024-05-13 15:39 UTC
